@ECHO OFF
echo www.github.com/mondomata:::ONLY HUNGARIAN LANG::::::::::::::::::::::
echo Microsoft Office 2024 Pro Plus telepito 64bit-es Windows 10,11-re
echo MAGYAR NYELVU WORD, EXCEL, POWERPOINT (sallangok nelkul :-)
echo ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
echo !!! Ezzel a parancs fajllal 1 (azonos) konyvtarban legyenek:
echo OfficeSetup.exe , configWordExcelPowerpointHUN.xml
echo Ha kesz, nyomj le egy billentyut es kezdunk...
echo ____________________________________________________________________
PAUSE
OfficeSetup.exe /configure configWordExcelPowerpointHUN.xml
echo Ha mindent jol csinaltal, az Office telepites kulon ablakban elindult, par perc es kesz...
echo Ezt az ablakot bezarhatod.
